sudo: false
language: node_js
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE maindb;'
node_js:
  - '10'
install:
  - npm i npminstall && npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
